name: CSS Lint

on: 
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - '**/*.css'

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm run stylelint
