name: JavaScript Lint

on:
  push:
    paths:
      - '**/*.js'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.js'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: lint
        run: |
          npm install
          npm run lint
