name: Run Python Lint

on: 
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  javascript-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm run lint
      - run: npm run stylelint
      - run: npm run markdownlint
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pip install pylint==2.2.3 requests==2.22.0 PyYAML==5.1.2 black==19.10b0
      - run: pylint **/*.py --errors-only
      # MAJOR TODO: INCLUDE --CHECK
      - run: black **/*.py --line-length 100 --diff
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: npm install
      - run: npm test
