name: Markdown Lint

on:
  push:
    branches:
    paths:
      - '**/*.md'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: markdownlint
        run: |
          npm install
          npm run markdownlint
