name: Python Lint

on:
  push:
    paths:
      - '**/*.py'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.py'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: black
        run: |
          pip install black==19.10b0 PyYAML==5.1.2 requests==2.22.0
          black **/*.py --line-length 100 --check --diff
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: pylint
        run: |
          pip install pylint==2.2.3 PyYAML==5.1.2 requests==2.22.0
          pylint **/*.py --errors-only
