name: Create Release Artifact

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize    

jobs:
  create-release:
    runs-on: windows-latest
    if: ${{ github.repository == 'panicstevenson/cactapot' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: ./util/fetch_deps.py
      - run: dotnet build plugin/Cactbot.sln /p:Configuration=Release /p:Platform=x64
      - run: ./util/publish.sh
